// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ve3fk7XJtFPmTWUA1GyigJtAIIj5zPg',
    appId: '1:931630937908:web:b496d923453693c56d5761',
    messagingSenderId: '931630937908',
    projectId: 'ecommercephpapp',
    authDomain: 'ecommercephpapp.firebaseapp.com',
    storageBucket: 'ecommercephpapp.appspot.com',
    measurementId: 'G-P5G1Q5KSTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnf4Aa9E6y8Kn9lkIi09TkmYbfjApHOt8',
    appId: '1:931630937908:android:bdf8b69c4c7b7ff66d5761',
    messagingSenderId: '931630937908',
    projectId: 'ecommercephpapp',
    storageBucket: 'ecommercephpapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8yB1ZjoCYpg9qLUb92Legs3sG42ib10',
    appId: '1:931630937908:ios:13adc5b76b37c2716d5761',
    messagingSenderId: '931630937908',
    projectId: 'ecommercephpapp',
    storageBucket: 'ecommercephpapp.appspot.com',
    iosClientId: '931630937908-82k6sd3k32p9jgcrc6et5kr0ikcaccnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf8yB1ZjoCYpg9qLUb92Legs3sG42ib10',
    appId: '1:931630937908:ios:28dfd89a69b4deb76d5761',
    messagingSenderId: '931630937908',
    projectId: 'ecommercephpapp',
    storageBucket: 'ecommercephpapp.appspot.com',
    iosClientId: '931630937908-p2nonabh9tsaf3lhd70juj895sela1b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApplication.RunnerTests',
  );
}
